services:
  authentik-server:
    image: 'ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2025.10.3}'
    restart: unless-stopped
    command: server
    environment:
      - SERVICE_URL_AUTHENTIKSERVER_9000
      - 'AUTHENTIK_POSTGRESQL__HOST=${POSTGRES_HOST:-postgresql}'
      - 'AUTHENTIK_POSTGRESQL__USER=${SERVICE_USER_POSTGRESQL}'
      - 'AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'AUTHENTIK_SECRET_KEY=${SERVICE_PASSWORD_64_AUTHENTIKSERVER}'
      - 'AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED:-true}'
      - 'AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}'
      - 'AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}'
      - 'AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}'
      - 'AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}'
      - 'AUTHENTIK_EMAIL__USE_TLS=${AUTHENTIK_EMAIL__USE_TLS}'
      - 'AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}'
      - 'AUTHENTIK_EMAIL__TIMEOUT=${AUTHENTIK_EMAIL__TIMEOUT}'
      - 'AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}'
    volumes:
      - './media:/media'
      - './custom-templates:/templates'
    networks:
      - coolify
    depends_on:
      postgresql:
        condition: service_healthy
  authentik-worker:
    image: 'ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2025.10.3}'
    restart: unless-stopped
    command: worker
    environment:
      - 'AUTHENTIK_POSTGRESQL__HOST=${POSTGRES_HOST:-postgresql}'
      - 'AUTHENTIK_POSTGRESQL__USER=${SERVICE_USER_POSTGRESQL}'
      - 'AUTHENTIK_POSTGRESQL__NAME=${POSTGRES_DB:-authentik}'
      - 'AUTHENTIK_POSTGRESQL__PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'AUTHENTIK_SECRET_KEY=${SERVICE_PASSWORD_64_AUTHENTIKSERVER}'
      - 'AUTHENTIK_ERROR_REPORTING__ENABLED=${AUTHENTIK_ERROR_REPORTING__ENABLED}'
      - 'AUTHENTIK_EMAIL__HOST=${AUTHENTIK_EMAIL__HOST}'
      - 'AUTHENTIK_EMAIL__PORT=${AUTHENTIK_EMAIL__PORT}'
      - 'AUTHENTIK_EMAIL__USERNAME=${AUTHENTIK_EMAIL__USERNAME}'
      - 'AUTHENTIK_EMAIL__PASSWORD=${AUTHENTIK_EMAIL__PASSWORD}'
      - 'AUTHENTIK_EMAIL__USE_TLS=${AUTHENTIK_EMAIL__USE_TLS}'
      - 'AUTHENTIK_EMAIL__USE_SSL=${AUTHENTIK_EMAIL__USE_SSL}'
      - 'AUTHENTIK_EMAIL__TIMEOUT=${AUTHENTIK_EMAIL__TIMEOUT}'
      - 'AUTHENTIK_EMAIL__FROM=${AUTHENTIK_EMAIL__FROM}'
    user: root
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './media:/media'
      - './certs:/certs'
      - './custom-templates:/templates'
    networks:
      - coolify
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    image: 'postgres:16-alpine'
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}'
      interval: 2s
      timeout: 10s
      retries: 15
    volumes:
      - 'authentik-db:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRESQL}'
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRESQL}'
      - POSTGRES_DB=authentik
    networks:
      - coolify
volumes:
  authentik-db: null
networks:
  coolify:
    external: true
